// manually created missing metadata
interface Metadata {
  description?: string
  label?: string
}
const metadata: Map<string, Metadata> = new Map([
  ['acl', {description: 'Ontology for authorization using access-control list.', label: 'ACL'}],
  ['cc', {description: 'The Creative Commons Rights Expression Language (CC REL) lets you describe copyright licenses in RDF. For more information on describing licenses in RDF and attaching those descriptions to digital works, see [CC REL](https://wiki.creativecommons.org/CC_REL) in the [Creative Commons wiki](https://wiki.creativecommons.org/).', label: 'Creative Commons'}],
  ['constant', {description: 'The Constants vocabulary defines terms for and contains the values and standard uncertainties of physical constants, initially populated from the NIST website: The NIST Reference on Constants, Units, and Uncertainty, at http://physics.nist.gov/cuu/index.html', label: 'QUDT Constants'}],
  ['crm', {description: 'The CIDOC Conceptual Reference Model (CRM) is a theoretical and practical tool for information integration in the field of cultural heritage. It can help researchers, administrators and the public explore complex questions with regards to our past across diverse and dispersed datasets. The CIDOC CRM achieves this by providing definitions and a formal structure for describing the implicit and explicit concepts and relationships used in cultural heritage documentation and of general interest for the querying and exploration of such data. Such models are also known as formal ontologies. These formal descriptions allow the integration of data from multiple sources in a software and schema agnostic fashion.', label: 'CIDOC Conceptual Reference Model'}],
  ['dc11', {description: 'This document is an up-to-date, authoritative specification of all metadata terms maintained by the Dublin Core™ Metadata Initiative. Included are the fifteen terms of the Dublin Core™ Metadata Element Set (also known as "the Dublin Core") plus several dozen properties, classes, datatypes, and vocabulary encoding schemes. The "Dublin Core" plus these extension vocabularies are collectively referred to as "DCMI metadata terms" ("Dublin Core terms" for short). These terms are intended to be used in combination with metadata terms from other, compatible vocabularies in the context of application profiles.'}],
  ['dcam', {description: 'This document is an up-to-date, authoritative specification of all metadata terms maintained by the Dublin Core™ Metadata Initiative. Included are the fifteen terms of the Dublin Core™ Metadata Element Set (also known as "the Dublin Core") plus several dozen properties, classes, datatypes, and vocabulary encoding schemes. The "Dublin Core" plus these extension vocabularies are collectively referred to as "DCMI metadata terms" ("Dublin Core terms" for short). These terms are intended to be used in combination with metadata terms from other, compatible vocabularies in the context of application profiles.'}],
  ['dcmitype', {description: 'The set of classes specified by the DCMI Type Vocabulary, used to categorize the nature or genre of the resource.'}],
  ['dcterms', {description: 'The /terms/ namespace was originally created in 2001 for identifying new terms coined outside of the original fifteen-element Dublin Core. In 2008, in the context of defining formal semantic constraints for DCMI metadata terms in support of RDF applications, the original fifteen elements themselves were mirrored in the /terms/ namespace. As a result, there exists both a dc:date (http://purl.org/dc/elements/1.1/date) with no formal range and a corresponding dcterms:date (http://purl.org/dc/terms/date) with a formal range of "literal". While these distinctions are significant for creators of RDF applications, most users can safely treat the fifteen parallel properties as equivalent. The most useful properties and classes of DCMI Metadata Terms have now been published as ISO 15836-2:2019 [ISO 15836-2:2019]. While the /elements/1.1/ namespace will be supported indefinitely, DCMI gently encourages use of the /terms/ namespace.'}],
  ['dig', {description: 'RM Digital is an ontology and RDF Schema to encode metadata about the steps and methods of production ("provenance") of digitization products and synthetic digital representations such as 2D, 3D or even animated Models created by various technologies. Its distinct features compared to competitive models is the complete inclusion of the initial physical measurement processes and their parameters. It has been developed as compatible extension of CIDOC CRM, which allows for querying the most relevant facts and returning complete descriptions encoded in this model by generic ISO21127 terms without need to refer to its specific properties. In contrast, competitive models cannot be queried by a more general standard and are restricted to the computational provenance only. Data encoded in the major competitive models can be transformed without loss of meaning into a CRM-Digital-form.', label: 'CRM Digital'}],
  ['schema', {description: `Schema.org is a collaborative, community activity with a mission to create, maintain, and promote schemas for structured data on the Internet, on web pages, in email messages, and beyond.
Schema.org vocabulary can be used with many different encodings, including RDFa, Microdata and JSON-LD. These vocabularies cover entities, relationships between entities and actions, and can easily be extended through a well-documented extension model. Over 10 million sites use Schema.org to markup their web pages and email messages. Many applications from Google, Microsoft, Pinterest, Yandex and others already use these vocabularies to power rich, extensible experiences.`, label: 'Schema.org'}],
  ['sd', {description: 'This document describes SPARQL service description, a method for discovering, and vocabulary for describing SPARQL services made available via the SPARQL 1.1 Protocol for RDF [SPROT]. These descriptions provide a mechanism by which a client or end user can discover information about the SPARQL service such as supported extension functions and details about the available dataset.', label: 'SPARQL 1.1 Service Description'}],
  ['dpv', {description: 'The Data Privacy Vocabulary [DPV] enables expressing machine-readable metadata about the use and processing of personal data based on legislative requirements such as the General Data Protection Regulation [GDPR]. This document describes the DPV specification along with its data model.', label: 'Data Privacy Vocabulary'}],
  ['frbr', {description: `This vocabulary is an expression in RDF of the concepts and relations described in the IFLA report on the Functional Requirements for Bibliographic Records (FRBR).
This vocabulary is a work in progress, it includes RDF classes for the group 1, 2 and 3 entities described by the FRBR report and properties corresponding to the core relationships between those entities. It does not yet describe attributes of the entities. Where possible, appropriate relationships with other vocabularies are included in order to place this vocabulary in the context of existing RDF work.`, label: 'Functional Requirements for Bibliographic Records (FRBR)'}],
  ['geof', {label: 'GeoSPARQL Functions'}],
  ['geor', {label: 'GeoSPARQL rules'}],
  ['grddl', {description: 'GRDDL is a technique for gleaning resource descriptions from dialects of languages. It\'s a way of extracting Semantic Web data in RDF from XML formats (especially XHTML dialects or [microformats](http://www.microformats.org/)) via transformations identified by URIs and typically expressed in XSLT. For full details, see the [GRDDL specification](http://www.w3.org/2003/g/data-view#grddl_spec).', label: 'GRDDL Data Views'}],
  ['gs1', {description: 'The GS1 Web Vocabulary collects terms defined in various GS1 standards and data systems and made available for general use following Linked Data principles. It is designed as an extension to schema.org and, where relevant, mappings and relationships arising from that vocabulary are made explicit.', label: 'GS1 Web Vocabulary'}],
  ['ical', {description: 'The Internet Calendaring and Scheduling Core Object Specification (iCalendar) is a media type which allows users to store and exchange calendaring and scheduling information such as events, to-dos, journal entries, and free/busy information,[1] and together with its associated standards has been a cornerstone of the standardization and interoperability of digital calendars across different vendors.', label: 'Internet Calendaring and Scheduling Core Object Specification (iCalendar)'}],
  ['la', {description: 'Linked Art is a Community working together to create a shared Model based on Linked Open Data to describe Art. We then implement that model in Software and use it to provide valuable content. It is under active development and we welcome additional partners and collaborators.', label: 'Linked Art'}],
  ['list', {label: 'Semantic Web Application Platform - List'}],
  ['math', {label: 'Semantic Web Application Platform - Math'}],
  ['log', {label: 'Semantic Web Application Platform'}],
  ['ma', {label: 'Ontology for Media Resources'}],
  ['og', {label: 'The Open Graph protocol', description: 'The Open Graph protocol enables any web page to become a rich object in a social graph. For instance, this is used on Facebook to allow any web page to have the same functionality as any other object on Facebook.'}],
  ['pim', {label: 'Workspace Ontology', description: `This ontology is for use in describing
Workspaces.  Workspaces are places where data is stored and associated policies of privacy.
A given application typically stores information in several different
workspaces, some being user private, some shared, and some public.
it is crucial that the user has easy control over the destiny of information.`}],
  ['prefix', {label: 'QUDT Prefixes Version 2.1 Vocabulary', description: 'The Prefixes vocabulary defines the prefixes commonly prepended to units to connote multiplication, either decimal or binary.'}],
  ['qkdv', {label: 'QUDT Dimension Vectors Version 2.1 Vocabulary', description: 'Provides the set of all dimension vectors'}],
  ['quantitykind', {description: 'Provides the set of all quantity kinds.'}],
  ['qudt', {label: 'QUDT Schema', description: 'The QUDT, or \"Quantity, Unit, Dimension and Type\" schema defines the base classes properties, and restrictions used for modeling physical quantities, units of measure, and their dimensions in various measurement systems. The goal of the QUDT ontology is to provide a unified model of, measurable quantities, units for measuring different kinds of quantities, the numerical values of quantities in different units of measure and the data structures and data types used to store and manipulate these objects in software.'}],
  ['rdau', {description: 'Properties that are derived from the elements of all of the RDA entities with semantics that are independent of the IFLA Library Reference Model.'}],
  ['rdfs', {description: 'RDF Schema provides a data-modelling vocabulary for RDF data. RDF Schema is an extension of the basic RDF vocabulary.'}],
  ['rss', {label: 'RDF Site Summary (RSS)', description: 'RDF Site Summary (RSS) is a lightweight multipurpose extensible metadata description and syndication format. RSS is an XML application, conforms to the W3C\'s RDF Specification and is extensible via XML-namespace and/or RDF based modularization.'}],
  ['sem', {label: 'The Simple Event Model Ontology', description: 'This document describes an ontology for modelling events. Events are central elements in the representation of data from a variety of domains. Examples of these domains are history, cultural heritage, geography and multimedia. Event-centered modeling captures the time and place aspects of a domain. In addition, events provide a way to describe complicated relations between people, places, actions and objects.'}],
  ['set', {label: 'Semantic Web Application Platform - Set'}],
  ['string', {label: 'Semantic Web Application Platform - String'}],
  ['sou', {description: 'QUDT Systems of Units Vocabulary Version'}],
  ['unit', {label: 'Semantic Web Application Platform - Unit'}],
  ['void', {label: 'Vocabulary of Interlinked Datasets (VoID)', description: 'The Vocabulary of Interlinked Datasets (VoID) is an RDF Schema vocabulary for expressing metadata about RDF datasets. It is intended as a bridge between the publishers and users of RDF data, with applications ranging from data discovery to cataloging and archiving of datasets. This document provides a formal definition of the new RDF classes and properties introduced for VoID.'}],
  ['xsd', {label: 'XML Schema Definition', description: 'XSD (XML Schema Definition), a recommendation of the World Wide Web Consortium (W3C), specifies how to formally describe the elements in an Extensible Markup Language (XML) document. It can be used by programmers to verify each piece of item content in a document, to assure it adheres to the description of the element it is placed in.'}],
])

export default metadata